title: "SPONGE"
email: tim-lukas.habich@imes.uni-hannover.de
description: >-
  Open Source Designs of Articulated Soft Robots
github_username: tlhabich
remote_theme: pmarsceill/just-the-docs
color_scheme: "theme"
